<div class="content-wrapper clear-self">

  <main role="main" class="main">
    <div class="content">
      <div class="content-inner">

        <h1>Контакты</h1>

        <div class="localcontacts">
            <div class="phone">
              <p>
                <strong>Телефон</strong>
                <div>+7 (3822) 250-200</div>
                <div class="phone-description">
                  <i class="fa fa-clock-o" aria-hidden="true"></i>
                  <span>Прием звонков: с 9:00 до 20:00 (Пн-Пт)</span>
                </div>
              </p>
            </div>
            <div class="address">
              <strong>Адрес</strong>
              <p>Россия, 125040, г. Москва, Ленинский проспект, дом, строение, номер кабинета</p>
            </div>
            <div class="requisites">
              <strong>Реквизиты компании</strong>
              <p>ООО "Лекс Про" Юридический адрес: Россия, 634000, г. Томск, ул. Советская, 69 ОГРН 12345678910</p>
            </div>
            <div class="social">
              <strong>Мы в соц сетях</strong>
              <div class="social-items">
                <a class="vk" target="_blank" href="https://vk.com/lexprovtomske"></a>
                <a class="fb" target="_blank" href="http://facebook.com/"></a>
                <a class="tw" target="_blank" href="https://twitter.com/"></a>
                <a class="ok" target="_blank" href="http://www.odnoklassniki.ru/"></a>
              </div>
            </div>
            <div class="clear"></div>
            <div class="map">
              <script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=WfbbwuqwiPem4vIAoHIvZg_vuWIfTsuk&amp;width=960&amp;height=300&amp;lang=ru_RU&amp;sourceType=constructor"></script>
            </div>
          </div>
        </div>
      </div> <!-- .content-inner -->
    </div> <!-- .content -->
  </main> <!-- .main -->
</div>
