      <div class="footer-container clear-self">
        <div class="footer-container-inner">
          <div class="contacts">
            <div class="block-title">Контакты:</div>
            <div class="block-body clear-self">
              <div class="block-body__address"><p>Россия, 634000, г. Томск, ул.Советская, 69</p></div>
              <div class="block-body__phones-wr">
                Телефон:
                <div class="block-body__phones">
                  <div><a href="tel:+7 (3822) 250-200">250-200</a></div>
                </div>
              </div>
            </div>
          </div>
          <div class="feedback"></div>
        </div>
      </div>
      <footer role="contentinfo" class="footer">
        <div class="footer-inner clear-self">
          <div class="site-name">
            Copyright &copy; 2016 Lex Pro
          </div>
          <div class="footer-clear"></div>
        </div>
      </footer><!-- .footer -->
    </div> <!-- .site-wrapper -->
  </body>
</html>
