<div class="block-edit">
  <h1 class="block-title">Надежные юристы в Томске</h1>
  <div class="block-body clear-self"><p>Ну тут какой нибудь текст кароч.</p></div>
</div>
<div class="advantage">
  <ul class="advantage-list">
    <li><p><i class="fa fa-check" aria-hidden="true"></i>15-летний опыт защиты в судах и на переговорах.</p></li>
    <li><p><i class="fa fa-check" aria-hidden="true"></i>Высшее юридическое образование и дополнительные специальные знания в областях автотехники и оценки восстановительного ремонта автомобилей.</p></li>
    <li><p><i class="fa fa-check" aria-hidden="true"></i>Методика профессиональной медиации.</p></li>
  </ul>
</div>
<div style="clear:both;margin: 20px auto; width: 640px;"> <!-- styles move to css -->
  <a class="flamp-widget" href="http://tomsk.flamp.ru/firm/leks_pro_ooo_yuridicheskaya_kompaniya-70000001022539974"  data-flamp-widget-type="big" data-flamp-widget-count="3" data-flamp-widget-id="70000001022539974" data-flamp-widget-width="100%">Отзывы о нас на Флампе</a><script>!function(d,s){var js,fjs=d.getElementsByTagName(s)[0];js=d.createElement(s);js.async=1;js.src="//widget.flamp.ru/loader.js";fjs.parentNode.insertBefore(js,fjs);}(document,"script");</script>
</div>
